### ISSUE TITLE
Shape index measures don't use geodetic calculations

### ISSUE THREAD

**Issue by leehach** [r-barnes/compactnesslib#2]
compactnesslib performs Euclidean calculations. If the user submits data in lat-long coordinates, the Polsby-Popper and Schwartzberg measures will be off by a few percent.

See https://github.com/gerrymandr/compactr/blob/master/demo/testCrsShapeIndex.R for more information and a comparison using Pennsylvania districts.

**Comment by r-barnes** [comment]
This is by design.

compactnesslib assumes that you have projected into an appropriate Euclidean space prior to performing calculations. Some consequences of projection choice are discussed [here](https://arxiv.org/abs/1803.02857). The `README.md` has been updated to note this.

**Comment by leehach** [comment]
As doing these measurements using an appropriate geodetic calculation would be acceptable, I'm going to reopen and suggest that this be marked as an Enhancement.

Apologies for reopening. Feel free to close if this is not something you want to consider.

**Comment by r-barnes** [comment]
I think that, problematically, this would require maintaining an additional set of geospatial primitives for performing the geodetic calculations.

It also invites a host of questions about whether a sphere, WGS84 ellipsoid, or some other shape is being used. Answering this completely would require bundling something like Proj into the library.

Given that appropriate Euclidean projections provide answers close to the geodetic for all electoral districts, I think the foregoing would lead to technical and maintenance difficulties without significant benefit.
