### ISSUE TITLE
Area-based measures should not be performed in lat-long coordinates

### ISSUE THREAD

**Issue by leehach** [r-barnes/compactnesslib#3]
compactnesslib does all its calculations in Euclidean space. This will yield incorrect calculations for the area-based measures. For Convex Hull the difference is trivial. For Reock, the difference is major, and the direction is unpredictable.

Note, this is not fixable. Rather, the appropriate solution is to raise a warning (or error?) that the calculation should be performed on lat-long coordinates.

For more info see https://github.com/gerrymandr/compactr/blob/master/demo/testCrsAreaBased.R

**Comment by r-barnes** [comment]
This is by design.

compactnesslib assumes that you have projected into an appropriate Euclidean space prior to performing calculations. Some consequences of projection choice are discussed [here](https://arxiv.org/abs/1803.02857). The `README.md` has been updated to note this.
